#!/usr/bin/python3

"""
Lê, na entrada padrão, um programa na linguagem de montagem da máquina
virtual e retorna um programa em C que executa este programa.

Uso:
    montador < entrada > saida
"""

############### COMO RODAR: python3 montador fibo #####################
# Gera o arquivo em C compilável com o vetor de instruçoes de maquina #
from sys import argv

file = open("motor.c", "w")
ip = 0
v = () # vetor de instruçoes
tabsim = {}

file.write("#include <stdio.h>\n")
file.write("#include "+ '"maq.h"\n')
file.write("\nINSTR " + argv[1] + "[] = {\n")
with open(argv[1]) as f:
    for l in f:
        label = op = ""
        arg   = 0
        try:
            l = l[:l.index('#')]
        except:
            pass
        keys = l.split()
        if len(keys) > 0 and keys[0].endswith(":"):
            label = keys[0][:-1] # jogando fora o ':'
            tabsim[label]=ip
            keys.pop(0)
        if len(keys) > 0:
            op = keys.pop(0)
        if len(keys) > 0:
            arg = keys.pop(0)
            if arg in tabsim:
                arg = tabsim[arg]
        if op != "":
            file.write("  {%s, %s},\n"%(op,arg))
        else:
            file.write("\n")
        ip += 1
file.write("};\n\n")

file.write("""
int main(int ac, char **av) {
    Maquina *maq = cria_maquina(""" + argv[1] + """);
    exec_maquina(maq, 100);
    puts("---");
    exec_maquina(maq, 10);
    puts("---");
    destroi_maquina(maq);
    return 0;
}
""")
file.close()



# Local variables:
# mode: python
# End:
