#!/usr/bin/python3

"""
Lê, na entrada padrão, um programa na linguagem de montagem da máquina
virtual e retorna um programa em C que executa este programa.

Uso:
    montador < entrada > saida
"""

############### COMO RODAR: python3 montador in.txt ##################

from sys import argv

ip = 0
count = 0
v = [] # vetor de instruçoes
tabsim = {}

with open(argv[1]) as f:
    for l in f:
        label = op = ""
        arg   = 0
        try:
            l = l[:l.index('#')]
        except:
            pass
        keys = l.split()
        if len(keys) > 0 and keys[0].endswith(":"):
            label = keys[0][:-1] # jogando fora o ':'
            tabsim[label]=ip
            keys.pop(0)
        if len(keys) > 0:
            op = keys.pop(0)
        if len(keys) > 0:
            arg = keys.pop(0)
            if arg in tabsim:
                arg = tabsim[arg]
        if op != "":
            v.append((op, int(arg)))
        ip += 1
        count +=1
print(v)



# Local variables:
# mode: python
# End:
